[package]
org = "OpenLabs"
name = "solicitarAprovisionamentoRede"
version = "0.1.0"
distribution = "2201.7.1"

[build-options]
observabilityIncluded = true

[dependencies]
classpath = ["./lib"]

[[platform.java11.dependency]]
# Absolute or relative path of the JAR file.
path = "./lib/wlthint3client.jar"
